name: google-docs-to-local
description: Export Google Docs from Google Drive to local file system.
inputs:
  google_drive_folder_id:
    description: ID of the Google Drive folder to be exported.
    required: true
  output_directory_path:
    description: Directory path to output files.
    required: false
    default: output
runs:
  using: node16
  main: dist/index.js
